/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation(files("build/libs/StarSmith.jar"))
}

application {
    // Define the main class for the application.
    mainClassName = "kotlin.LALA.AppKt"
}

task<Exec>("translateSpec") {
    group = "generation"
    workingDir("$rootDir")
    val command = "./translate_spec.sh --spec spec/kotlin.ls --maxDepth 15 --toJava out/kotlin.java"
    commandLine(command.split(" "))
}

task<Exec>("compileSpec") {
    group = "generation"
    dependsOn("translateSpec")
    workingDir("${rootDir}/out")
    commandLine("./compile.sh", "kotlin.java")
}

task<Exec>("generateExamples") {
    group = "generation"
    dependsOn("compileSpec")
    workingDir("$rootDir")
    commandLine("./generate_examples.sh")
}
